server:
  port: 9000

spring:
  application:
    name: demo

  datasource:
    platform: mysql
    url: jdbc:mysql://mina.cpmk7sgo9jcp.ap-northeast-2.rds.amazonaws.com/Carrot?autoReconnect=true # 변경해주세요
    username: mina # 변경해주세요
    password: Sylim12!! # 변경해주세요
    driver-class-name: com.mysql.cj.jdbc.Driver

#    security:
#      oauth2:
#        client:
#          registartion:
#            kakao:
#              client_id: c542e13c92062485564e91d141795de5
#              redirect_uri: "https://mina-sy.shop/app/users/login/kakao"
#              client-authentication-method: POST
#                authorization-grant-type: authorization_code
#                scope: profile_nickname, account_email
#                client-name: Kakao
#            provider:
#              kakao:
#                authorization_uri: https://kauth.kakao.com/oauth/authorize
#                token_uri: https://kauth.kakao.com/oauth/token
#                user-info-uri: https://kapi.kakao.com/v2/user/me
#                user_name_attribute: id